LEXICON = {'forward': '>>',
           'backward': '<<',
           '/start': '<b>你好，读者!</b>\n\n这是一个机器人，在这里你可以阅读你上传的书！\n\n要查看可用命令列表-输入 /help',
           '/help': '<b>这是一个阅读机器人</b>\n\n可用命令：\n\n/beginning - 转到书的开头\n/continue - 继续阅读\n/bookmarks - 查看书签列表\n/help - 有关机器人工作的帮助信息\n\n要保存书签-请点击页面编号按钮。\n\n<b>祝您阅读愉快！</b>',
           '/bookmarks': '<b>这是您的书签列表：</b>',
           'edit_bookmarks': '<b>编辑书签</b>',
           'edit_bookmarks_button': '❌ 编辑',
           'del': '❌',
           'cancel': '取消',
           'no_bookmarks': '您目前还没有任何书签。\n\n要将页面添加到书签 - 在阅读书籍时，点击该页面编号的按钮。\n\n/continue - 继续阅读',
           'cancel_text': '/continue - 继续阅读',
           }